apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.basic.name }}-sv"
  labels:
    app.kubernetes.io/name: "{{ .Values.basic.name }}"
  namespace: "{{ .Values.basic.namespace }}"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ .Values.basic.name }}"