name: Build and publish

on:
  release:
    types: [ published ]

jobs:

  docker-build-and-publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . -t z9pascal/container-manager-oidc-gatekeeper:$(cat ./Dockerfile | grep -Po 'version="\K.*?(?=")')-latest

      - name: Relase the Docker image
        run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u z9pascal --password-stdin && docker push z9pascal/container-manager-oidc-gatekeeper:$(cat ./Dockerfile | grep -Po 'version="\K.*?(?=")')-latest
